/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import Validation.Validations;
import dbconnection.dbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.text.SimpleDateFormat;
import java.util.ArrayList;
//import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GanapriyaS
 */
public class payment extends javax.swing.JFrame {

    /**
     * Creates new form payment
     */
    HashMap<Integer,ArrayList> hm;
    Modal.empDetails ed;
     DefaultTableModel dtm;
    boolean b=false;
    int tot=0;
     String name;
    int row=-1;
    int n=0;
    Validations v=new Validations();
    public payment(Modal.empDetails ed,HashMap<Integer,ArrayList> hm) {
        this.ed=ed;
        this.hm=hm;
        initComponents();
        dtm=(DefaultTableModel)jTable1.getModel();
        for(Map.Entry m:hm.entrySet())
        {   
            n=n+1;
//            getvalue returns arraylist
            ArrayList al=(ArrayList)m.getValue();
            Object[] o={n,al.get(0),al.get(1),al.get(2),al.get(3),al.get(4),al.get(5),m.getKey()};
            dtm.addRow(o);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CUSTOMER PHONE NO :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CUSTOMER NAME :");

        jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 0, 0));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("TOTAL BILL :");

        jLabel4.setBackground(new java.awt.Color(51, 255, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("____________________________");

        jComboBox1.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select payment mode", "Cash", "Card" }));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BILLING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Item id", "Item Name", "Price", "Category", "Quantity", "Total price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cart c=new cart(ed,hm);
        c.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        b=false;
        String phoneno=jTextField1.getText();
        
        if(!phoneno.equals(""))
                {
       
        try(Connection con=dbConnection.getConnect();
                PreparedStatement ps=con.prepareStatement("select * from customer where phoneno='"+phoneno+"'");
                ResultSet rs=ps.executeQuery();)
        {
            if(rs.next())
            {   
                name=rs.getString("name");
                jTextField2.setText(name);
                JOptionPane.showMessageDialog(rootPane,"Customer already visited!");
                b=true;                         
            }
            else
            {
                jTextField2.setText("");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
          }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int tot=0;
        for(Map.Entry m:hm.entrySet())
        {   
            ArrayList al=(ArrayList)m.getValue();
            tot+=Integer.parseInt((String)al.get(5));
        }
        jLabel4.setText(String.valueOf(tot));
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i=-1,j=-1;
        if(!jTextField1.getText().equals("") && !jTextField2.getText().equals("") && jComboBox1.getSelectedIndex()!=0 )
        {
            if(!v.nameValidate(jTextField2.getText()))
        {
             JOptionPane.showMessageDialog(rootPane,"Name is not valid \n Min 3 to Max 25 characters \n Contain only capital or small alphabets!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!v.phoneValidate(jTextField1.getText()))
        {
             JOptionPane.showMessageDialog(rootPane,"Phoneno is not valid \n Should have 10 characters \n Contain only numbers 0-9","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        if(b==false)
        {
            
        try(Connection con=dbConnection.getConnect();
                PreparedStatement ps=con.prepareStatement("insert into customer(phoneno,name) values(?,?)");
            )
        {   
            
            ps.setString(1, jTextField1.getText());
            ps.setString(2, jTextField2.getText());
            
            i=ps.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(rootPane,"Customer data inserted!");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Customer data not inserted!","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        }
        else{
            if(!jTextField2.getText().equals(name))
            {   
        int h=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to update this customer details?");
        if(h==0)
        {
              
                try(Connection con=dbConnection.getConnect();
                PreparedStatement ps=con.prepareStatement("update customer set name=? where phoneno=?");
            )
        {   
            
            ps.setString(1, jTextField2.getText());    
            ps.setString(2, jTextField1.getText());    
            i=ps.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(rootPane,"Customer data updated!");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Customer data not updated!","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            }
            }
        }
        
//        Date d=new Date();
//        SimpleDateFormat s=new SimpleDateFormat("dd/mm/yyyy");
//        String date1=s.format(d);
//        
//        SimpleDateFormat s1=new SimpleDateFormat("hh:mm:ss");
//        String date2=s1.format(d);
                
                try(Connection con1=dbConnection.getConnect();
                        PreparedStatement ps1=con1.prepareStatement("insert into shopping(name,phoneno,details,mode,biller) values(?,?,?,?,?)");
                        )
                {
                    ps1.setString(1, jTextField2.getText());
                    ps1.setString(2, jTextField1.getText());
                    ps1.setString(3, hm.toString());
                    ps1.setString(4, (jComboBox1.getSelectedItem()).toString());
                    ps1.setString(5, (ed.getName()));
//            ps.setString(3, date1);
//            ps.setString(4, date2);
              j=ps1.executeUpdate();
              if(j>0)
              {
                  JOptionPane.showMessageDialog(rootPane,"Shopping details added!");
              }
              else{
              JOptionPane.showMessageDialog(rootPane,"Shopping details not added!","Error",JOptionPane.ERROR_MESSAGE);
              }
                }
                catch(Exception e)
                {
                    System.out.println(e);
                } 
        if( j>0 &&( i>0 || b==true))
        {
        JOptionPane.showMessageDialog(rootPane,"Thank you for shopping....Visit again");
        profile p=new profile(ed);
        p.setVisible(true);
        setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Enter customer details properly!","Error",JOptionPane.ERROR_MESSAGE);
        }
        }}
        else{
            JOptionPane.showMessageDialog(rootPane,"Enter customer details!","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
